# Netlify Build Settings

# Build command (not needed for static HTML)
# build = ""

# Publish directory
publish = "."

# Redirect rules for specific paths
[[redirects]]
  from = "/admin"
  to = "/boost.html"
  status = 200

# Handle 404s but don't interfere with existing HTML files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' https://gijhfdjsmlgivjhvbtve.supabase.co wss://gijhfdjsmlgivjhvbtve.supabase.co; worker-src 'self' blob:; child-src 'self' blob: data:; frame-src 'self' blob: data:;"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
